<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="login"
    errors="0" failures="1" hostname="" id="" package="login" skipped="0"
    tests="1" time="8.424" timestamp="Sat, 10 Mar 2018 20:55:25 GMT">
  
    <testcase name="function" classname="login" time="8.424" assertions="1">  <failure message="Timed out while waiting for element &lt;#app&gt; to be present for 5000 milliseconds.">    at Object.function (D:\Users\Gebruiker\Documents\School\Kdg3\Integratieproject 2\frontend\Nextup_frontend\tests\login.js:5:8)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)</failure>

    
    </testcase>
  

  

  
  </testsuite>
</testsuites>
